"""Stable SafetyViolation code catalog (generic package)."""

from __future__ import annotations

POLICY_DENY_ALL = "POLICY_DENY_ALL"
PATH_ESCAPE = "PATH_ESCAPE"
PATH_DENIED = "PATH_DENIED"
PATH_PROTECTED = "PATH_PROTECTED"
PATH_UNEXPECTED = "PATH_UNEXPECTED"
ACTION_PROHIBITED = "ACTION_PROHIBITED"
CONFIG_INVALID = "CONFIG_INVALID"

__all__ = [
    "ACTION_PROHIBITED",
    "CONFIG_INVALID",
    "PATH_DENIED",
    "PATH_ESCAPE",
    "PATH_PROTECTED",
    "PATH_UNEXPECTED",
    "POLICY_DENY_ALL",
]
